---
# kics-scan ignore
name: Pull Request CI

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: 17
  ATALA_GITHUB_ACTOR: ${{ secrets.ATALA_GITHUB_ACTOR }}
  ATALA_GITHUB_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os-type: linux
          - os: macos-13
            os-type: macos
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Validate Gradle Wrapper"
        run: pwd

      - name: "Checkout the repo"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ATALA_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: "Install Java ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "zulu"

      - name: "Gradle Build Action"
        uses: gradle/gradle-build-action@v3

      - name: "Install Homebrew"
        if: matrix.os-type == 'macos'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: "Install autoconf, automake, libtool"
        if: matrix.os-type == 'macos'
        run: |
          brew install autoconf automake libtool

      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os-type == 'macos'
        with:
          xcode-version: '15.0.1'

      - name: "Install rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: "Install wasm-pack"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack
          

      - name: "Test Kotlin code is properly formatted"
        run: ./gradlew ktlintCheck

      - name: "Build Check All tests"
        run: ./gradlew allTests

      - name: "Generate kover coverage report"
        run: ./gradlew koverHtmlReport koverXmlReport

      - name: "Upload coverage html"
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-results-${{ matrix.os-type }}.zip
          path: apollo/build/reports/kover/html

      - name: "Add coverage report to PR"
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/apollo/build/reports/kover/report.xml
          token: ${{ secrets.ATALA_GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 90
          min-coverage-changed-files: 90
          coverage-counter-type: LINE

      - name: "Upload the build report"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: "**/build/reports/"
          name: report-${{ matrix.os-type }}
